### ISSUE TITLE
berkshelf commands are broken using the dep_selector-1.0.1 gem on centOS

### ISSUE THREAD

**Issue by etherealiska** [chef/dep-selector#23]
I already fixed my issue by installing dep_selector-1.0.0 first, and then installing berkshelf. This is on a CentOS 6.4 machine. I wish I had more info but I'm new to this kind of stuff. Berkshelf was installed on this chef server using the chef client, which I assume is how gem_package resource works.

$ /opt/chef/embedded/bin/gem install berkshelf

The error comes from any berks command, even just getting the version number. 

$ /opt/chef/embedded/bin/berks -v

``` text
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ffi-1.9.3/lib/ffi/library.rb:133:in `block in ffi_lib': Could not open library '/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/dep_selector-1.0.1/lib/dep_gecode.so': libgecodesearch.so.32: cannot open shared object file: No such file or directory (LoadError)
    from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ffi-1.9.3/lib/ffi/library.rb:100:in `map'
    from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ffi-1.9.3/lib/ffi/library.rb:100:in `ffi_lib'
    from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/dep_selector-1.0.1/lib/dep_selector/dep_gecode.rb:39:in `<module:Dep_gecode>'
    from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/dep_selector-1.0.1/lib/dep_selector/dep_gecode.rb:21:in `<top (required)>'
    from /opt/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/dep_selector-1.0.1/lib/dep_selector/gecode_wrapper.rb:21:in `<top (required)>'
    from /opt/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/dep_selector-1.0.1/lib/dep_selector/dependency_graph.rb:21:in `<top (required)>'
    from /opt/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/dep_selector-1.0.1/lib/dep_selector/selector.rb:21:in `<top (required)>'
    from /opt/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/dep_selector-1.0.1/lib/dep_selector.rb:22:in `<top (required)>'
    from /opt/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/solve-1.1.0/lib/solve/solver.rb:1:in `<top (required)>'
    from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/solve-1.1.0/lib/solve.rb:10:in `require_relative'
    from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/solve-1.1.0/lib/solve.rb:10:in `<module:Solve>'
    from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/solve-1.1.0/lib/solve.rb:3:in `<top (required)>'
    from /opt/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/berkshelf-3.0.1/lib/berkshelf.rb:8:in `<top (required)>'
    from /opt/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /opt/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/berkshelf-3.0.1/lib/berkshelf/cli.rb:1:in `<top (required)>'
    from /opt/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /opt/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/berkshelf-3.0.1/bin/berks:3:in `<top (required)>'
    from /opt/chef/embedded/bin/berks:23:in `load'
    from /opt/chef/embedded/bin/berks:23:in `<main>'
```

**Comment by schovi** [comment]
+1 Debian 8.1 jessie

**Comment by cloneluke** [comment]
I've had some issues in this area, did the following
gem uninstall dep_selector
gem uninstall dep-selector-libgecode

and then re-installed

**Comment by the-nose-knows** [comment]
@cloneluke Omg... why didn't I try that an hour ago >_< lol...

Uninstalling both and then installed `dep_selector` unblocked me ^_^
